task: validation

data:
  batch_size: 32
  image_size: ${image_size}
  cpu_num: 1
  shuffle: False
  pin_memory: True
  data_augment: {}
  dynamic_shape: False
nms:
  min_confidence: 0.5
  min_iou: 0.5
  max_bbox: 300
